### PR TITLE
Rename nanover-protocol to nanover-server-py

### PR DESCRIPTION
**Pull request by Ragzouken**

### CODE REVIEW

**Comment by rhoslynroebuck** [comment]
I have gone through and updated the in-text uses of terms such as "NanoVer server", "NanoVer Protocol", and "Rust server" to make them consistent with the name changes (see the [commit message](https://github.com/IRL2/nanover-docs/pull/132/commits/800711d45a63186d466ad6a08c660e4c9bc5274e) for details). 

I have not yet addressed the [base-protocol page](https://github.com/IRL2/nanover-docs/blob/refactor/rename-protocol/source/concepts/base-protocol.rst), would you be able to take a look at this @Ragzouken? The other page that needs addressing is the Applications page, but this page is being worked on in a separated PR so let's leave that for this PR.

**Review by rhoslynroebuck — CHANGES_REQUESTED** [review]
I have gone through and updated the in-text uses of terms such as "NanoVer server", "NanoVer Protocol", and "Rust server" to make them consistent with the name changes (see the [commit message](https://github.com/IRL2/nanover-docs/pull/132/commits/800711d45a63186d466ad6a08c660e4c9bc5274e) for details).

I have not yet addressed the [base-protocol page](https://github.com/IRL2/nanover-docs/blob/refactor/rename-protocol/source/concepts/base-protocol.rst), would you be able to take a look at this @Ragzouken? The Applications page also needs addressing, but this page is being worked on in a separated PR so let's leave that for now.

**Comment by Ragzouken** [comment]
> I have not yet addressed the [base-protocol page](https://github.com/IRL2/nanover-docs/blob/refactor/rename-protocol/source/concepts/base-protocol.rst), would you be able to take a look at this @Ragzouken?

I've retitled to `NanoVer gRPC Protocol` and specified `gRPC services`--this seems like it covers the necessary changes for the rename?

**Comment by rhoslynroebuck** [comment]
Awesome, this is good to me. The rest of the page uses just "protocol", but I think it should be clear to a reader that this is short for "gRPC protocol".

**Review by rhoslynroebuck — APPROVED** [review]
This looks good to me.

**Pull request merged**
